sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-23
    - android-27
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock 

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - echo no | npm install -g grunt-cli
    - npm install
    - grunt compile

matrix:
  include:
    - stage: lint
      language: android
      jdk: oraclejdk8
      os: linux
      before_install: nvm install 8.11.3
      script: grunt lint

    - stage: build
      language: android
      os: linux
      env: 
        - Android="26"
      jdk: oraclejdk8
      before_install: nvm install 8.11.3
      script: "grunt ci:build:android"

    - stage: build
      os: osx
      env: 
        - iOS="11.4"
        - Xcode="9.4"
      osx_image: xcode9.4
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
      script: "grunt ci:build:ios"

    - stage: webpack
      language: android
      os: linux
      env:
        - Android="26"
        - Platform="Android"
      jdk: oraclejdk8
      before_install: nvm install 8.11.3
      script: "grunt ci:webpack:android"
    
    - stage: webpack
      os: osx
      env: 
        - iOS="11.4"
        - Xcode="9.4"
        - Platform="iOS"
      osx_image: xcode9.4
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
      script: "grunt ci:webpack:ios"

    - stage: deploy
      if: branch = release
      language: android
      jdk: oraclejdk8
      os: linux
      before_install: nvm install 8.11.3
      script: skip
      before_deploy:
          - cd bin/dist
      deploy:
        provider: npm
        email: "peter@tangrasoft.com"
        api_key:
          secure: "ndYaZ2oKCdBfEfeCwA74NwDXZnUGN8u40d+Pz86NBpABRQ+ZAArbVs7EfwP6dS1+T/9fCkBDhbYP0B08cLXOoB3c6P4Ibv8YjHbyu7a2Pr7YkFbgyzt7jOvXCyP9z11hoAuRnWa/tV1NfjX4pkJDyw9pH1bIhGb19GwEo4iv3mpsy02NPF2/fVH2+mQ5jsdwmCxJBihK9pXBXg7Z3L1s+N1hQiPRuu4CnjMrp9MozF2T6e3JIkECGFXGgq94n0M1WmtAZZDahG3wQ7lUVkl/sC67+n3OvPyOszlTC4mR+kXKY5kBkj1VFxhKUfV3XaW67C0M/Ys79m8NPvZPhNBdwprWICoqawTUeNenX6GWy+oENoGpEYLaQ9nWjqSBK+NBCXMuf8aAnVBniNfs1JRlUg3Es/1j8CNZcVJ9VkcsT9TRlOWPjD8zKAL/Fg9/k9UWOvsiYfr+zweGTytFvlnsuYoQQSZod5TFwEGMBA4UjXOrpXAL3CcTFvlW3+jK/JzVc1XJtl7Fuk75H3NUUxmBkSdjJz69JVhuKX83heSXlIzbRiBNnYODL5fyuiV+VQC60zGeJxUFLJaBmrTSgxBoocbR5jZY8r9dmAOfD6m46BQIIzHJ5BJ6/tWEf32SSB8aFfq3RqBiFZbUpy1grXVVImAclrKCUiseS5ZTOUe3QgY="
        skip_cleanup: true
        on:
          branch: release